name: Build Nekogram APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: false
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # ХАК: Создаем пустые файлы во всех папках, где их ищет проект
      - name: Create stub files
        run: |
          # Содержимое пустого google-services.json
          STUB_JSON='{"project_info":{"project_number":"1","project_id":"stub"},"client":[{"client_info":{"mobilesdk_app_id":"1:1:android:1","android_client_info":{"package_name":"tw.nekomimi.nekogram"}},"api_key":[{"current_key":"stub"}]}]}'
          
          # Кладем его в обе возможные папки
          mkdir -p TMessagesProj
          echo "$STUB_JSON" > TMessagesProj/google-services.json
          
          mkdir -p TMessagesProj_App
          echo "$STUB_JSON" > TMessagesProj_App/google-services.json
          
          # Настраиваем локальные пути к SDK
          touch local.properties
          echo "sdk.dir=$ANDROID_SDK_ROOT" >> local.properties
          echo "api_id=12345" >> local.properties
          echo "api_hash=stub" >> local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Собираем DEBUG версию
      - name: Build Debug APK
        run: |
          ./gradlew assembleDebug \
          -Dorg.gradle.parallel=false \
          -Dorg.gradle.workers.max=1 \
          -Dorg.gradle.jvmargs="-Xmx4g" \
          --stacktrace

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Nekogram-Debug-APK
          path: "**/*.apk" # Искать все APK во всех подпапках